# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               annotatAR
tagline:             lo-fi augmented reality for the mobile web
url:                 http://arebe.github.io
paginate:            1
baseurl:             "/annotatar"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              RB
  url:               https://twitter.com/roastbeest
  email:             rfboyce+annotatar@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/arebe/annotatar
